config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  # devise_for :admin_users, controllers: {
  #   sessions: 'admins/sessions'
  # }
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  resources :financial_reports do
    collection do
      get :select_subdomain
    end
  end
  resources :subdomains, only: [:index, :show] do
    resources :financial_reports do
      resources :investigations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :reviews, only: [:index, :new, :create, :show, :update] do
          member do
            patch :approve
          end
        end
      end
      resources :reviews, only: [:index, :new, :create, :show, :update] do
        member do
          patch :approve
        end
      end
    end   
  end
  get '/sw.js', to: proc { [204, {}, []] }, constraints: ->(req) { Rails.env.development? }

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/financial_report.rb
class FinancialReport < ApplicationRecord
  # Enum for data types
  enum data_type: { external: 0, internal: 1 }

  # Associations
  belongs_to :subdomain, optional: true
  belongs_to :uploaded_by, class_name: 'User'
  has_many :reviews, dependent: :destroy  
  has_many :investigations, dependent: :destroy
  has_one_attached :attachment

  # Validations
  validates :amount, presence: true
  validates :amount, numericality: { less_than: 100_000_000, message: "must be less than 100 million" }
  validates :description, presence: true

  def self.ransackable_attributes(auth_object = nil)
      ["id", "subdomain_id", "data_type", "amount", "description", "uploaded_by_id", "created_at", "updated_at"]
    end
  
    def self.ransackable_associations(auth_object = nil)
      ["subdomain", "uploaded_by"]
    end
end

app/controllers/financial_reports_controller.rb
class FinancialReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_financial_report, only: [:show, :edit, :update, :destroy]
  before_action :set_subdomain, only: [:new, :edit, :index, :show, :create, :update, :destroy]

  def index
    if @subdomain
      @financial_reports = @subdomain.financial_reports
    else
      redirect_to select_subdomain_financial_reports_path, alert: 'Subdomain not found.'
    end
  end

  def select_subdomain
    if current_user.public_user?
      @subdomains = Subdomain.all
    else
      @subdomains = current_user.subdomains
    end
  end

  def show; end

  def new
    @financial_report = current_user.financial_reports.new
  end

  def create
    @financial_report = current_user.financial_reports.new(financial_report_params)
    @financial_report.subdomain_id = @subdomain.id

    if @financial_report.save
      redirect_to subdomain_financial_report_path(@subdomain, @financial_report), notice: 'Financial report created successfully.'
    else
      flash[:alert] = @financial_report.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @financial_report.update(financial_report_params)
      redirect_to subdomain_financial_report_path(@subdomain, @financial_report), notice: 'Financial report updated successfully.'
    else
      flash[:alert] = @financial_report.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @financial_report.destroy
    redirect_to subdomain_financial_reports_path(@subdomain), notice: 'Financial report deleted successfully.'
  end

  private

  def set_financial_report
    @financial_report = FinancialReport.find(params[:id])
  end

  def set_subdomain
    @subdomain = Subdomain.find_by(id: params[:subdomain_id])
  end

  def financial_report_params
    params.require(:financial_report).permit(:subdomain_id, :data_type, :amount, :description, :attachment)
  end
end

app/views/financial_reports/_form.html.erb
<div class="container mt-5 pb-5">
  <div class="row justify-content-center">
    <div class="col-md-8 mb-5">
      <div class="card shadow-lg border-0">
        <div class="card-header bg-primary text-white text-center">
          <h4 class="mb-0"><%= @financial_report.new_record? ? "Add Financial Details" : "Edit Financial Details" %></h4>
        </div>
        <div class="card-body p-4">
        <%= form_with(model: @financial_report, url: @financial_report.new_record? ? subdomain_financial_reports_path(@subdomain) : subdomain_financial_report_path(@subdomain, @financial_report), local: true, multipart: true) do |f| %>

            <!-- Data Type Field -->
            <div class="mb-4">
              <%= f.label :data_type, "Report Type", class: "form-label fw-bold" %>
              <%= f.select :data_type, FinancialReport.data_types.keys.map { |key| [key.capitalize, key] }, {}, class: "form-select" %>
            </div>
          
            <!-- Amount Field -->
            <div class="mb-4">
              <%= f.label :amount, "Amount", class: "form-label fw-bold" %>
              <%= f.number_field :amount, class: "form-control", placeholder: "Enter Amount", required: true %>
            </div>

            <!-- Description Field -->
            <div class="mb-4">
              <%= f.label :description, "Description", class: "form-label fw-bold" %>
              <%= f.text_area :description, class: "form-control", placeholder: "Enter Description", rows: 4, required: true %>
            </div>

            <!-- Attachment Field -->
            <div class="mb-4">
            <%= f.label :attachment, "Upload File", class: "form-label fw-bold" %>
            <% if @financial_report.attachment.attached? %>
              <p>Current File: 
                <%= link_to @financial_report.attachment.filename, rails_blob_path(@financial_report.attachment, disposition: "attachment"), class: "text-decoration-none fw-bold text-primary" %>
              </p>
              <%= f.file_field :attachment, class: "form-control mt-2" %>
              <small class="text-muted">Upload a new file to replace the existing one.</small>
            <% else %>
              <%= f.file_field :attachment, class: "form-control", required: true %>
            <% end %>
          </div>

            <!-- Submit Button -->
            <div class="text-center d-flex justify-content-center gap-3">
              <%= link_to "Cancel", subdomain_financial_reports_path, class: "btn btn-danger btn-sm px-4 fw-bold" %>
              <%= f.submit @financial_report.new_record? ? "Save" : "Update", class: "btn btn-primary btn-sm px-4 fw-bold" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/financial_reports/edit.html.erb
<%= render 'form' %>

app/views/financial_reports/index.html.erb
<div class="container mt-4">
  <h1 class="text-center mb-4">Financial Reports</h1>
  
  <% if current_user.local_admin? %>
    <%= link_to "New Financial Report", new_subdomain_financial_report_path(subdomain_id: params[:subdomain_id]), class: "btn btn-success btn-sm mb-3" %>
  <% end %>
  
  <table id="fdms-datatable" class="table table-striped table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Subdomain</th>
        <th>Type</th>
        <th>Amount</th>
        <th>Description</th>
        <th class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @financial_reports.each do |financial_report| %>
        <tr>
          <td><%= financial_report.id %></td>
          <td><%= financial_report.subdomain.name %></td>
          <td><%= financial_report.data_type.capitalize %></td>
          <td><%= number_to_currency(financial_report.amount) %></td>
          <td><%= financial_report.description %></td>
          <td>
            <div class="btn-group d-flex justify-content-center">
              <!-- View Financial Report -->
              <%= link_to "View", subdomain_financial_report_path(subdomain_id: params[:subdomain_id], id: financial_report.id), class: "btn btn-primary btn-sm mx-1" %>

              <!-- View Feedbacks -->
              <%= link_to "Feedbacks", subdomain_financial_report_reviews_path(subdomain_id: params[:subdomain_id], financial_report_id: financial_report.id), class: "btn btn-info btn-sm mx-1" %>

              <!-- View Investigations -->
              <%= link_to "Investigations", subdomain_financial_report_investigations_path(subdomain_id: params[:subdomain_id], financial_report_id: financial_report.id), class: "btn btn-secondary btn-sm mx-1" %>

              <!-- Edit and Delete only for non-public users -->
              <% unless current_user.iidm_admin? || current_user.public_user? %>
                <% if financial_report.uploaded_by_id == current_user.id %>
                  <%= link_to "Edit", edit_subdomain_financial_report_path(@subdomain,financial_report), class: "btn btn-warning btn-sm mx-1" %>
                  <%= button_to "Delete", subdomain_financial_report_path(subdomain_id: params[:subdomain_id], id: financial_report.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm mx-1" %>
                <% end %> 
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/financial_reports/new.html.erb
<%= render 'form' %>

app/views/financial_reports/select_subdomain.html.erb
<!-- app/views/financial_reports/select_subdomain.html.erb -->
<div class="container py-5">
  <h1 class="text-center mb-4 text-uppercase font-weight-bold">Subdomains</h1>
  
  <% if @subdomains.any? %>
    <div class="row">
      <% @subdomains.each do |subdomain| %>
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card shadow-sm h-100 border-0">
            <div class="card-body text-center">
              <h5 class="card-title text-primary mb-3 font-weight-bold">
                <%= subdomain.name.titleize %>
              </h5>
              <p class="card-text text-muted mb-4">
                <%= subdomain.description.presence || "No description available." %>
              </p>
              <%= link_to 'View Reports', subdomain_financial_reports_path(subdomain), 
                  class: 'btn btn-primary btn-block text-uppercase font-weight-bold', 
                  style: 'border-radius: 20px;' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="text-center my-5">
      <h3 class="text-muted">No Subdomains Available</h3>
      <p>It looks like there are no subdomains to display right now. Please check back later.</p>
    </div>
  <% end %>
</div>

app/views/financial_reports/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Financial Report</h2>
          <p class="card-text"><strong>Subdomain:</strong> <%= @financial_report.subdomain.name %></p>
          <p class="card-text"><strong>Type:</strong> <%= @financial_report.data_type.capitalize %></p>
          <p class="card-text"><strong>Amount:</strong> <%= number_to_currency(@financial_report.amount) %></p>
          <p class="card-text"><strong>Description:</strong> <%= @financial_report.description %></p>
          <% if @financial_report.attachment.attached? %>
          <p class="card-text">
            <strong>Attachment:</strong>
            <%= link_to "Download Attachment", rails_blob_path(@financial_report.attachment, disposition: "attachment"), class: "btn btn-secondary mt-3" %>
          </p>
        <% end %>
          <%= link_to "Back to Reports", subdomain_financial_reports_path(@subdomain), class: "btn btn-secondary mt-3" %>
          <% unless ["local_admin", "iidm_admin"].include?(current_user.role) %>
            <%= link_to "Give Feedback", new_subdomain_financial_report_review_path(@subdomain, financial_report_id: @financial_report.id), class: "btn btn-primary mt-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>